#!/usr/bin/env perl

sub blink {
    my @updatedStones = ();
    foreach my $stone (@_){
        my $stoneLength = length $stone;
        if ($stone == 0) {
            push @updatedStones,1;
        } elsif ($stoneLength % 2 == 0) {
            my $halfPoint = $stoneLength / 2;
            push @updatedStones, substr $stone, 0, $halfPoint;
            my $secondHalf = "";
            my @splitStone = split //,$stone;
            for my $i ($halfPoint..$stoneLength) {
                my $char = $splitStone[$i];
                if($char eq 0 && length $secondHalf == 0){
                    next;
                }  
                $secondHalf = $secondHalf.$char;
            }
            if(length $secondHalf == 0) {
                push @updatedStones, 0;
            } else {
                push @updatedStones, $secondHalf;
            }
        } else {
            push @updatedStones, $stone * 2024;
        }

    }
    my $updatedString = join ' ', @updatedStones;
    return @updatedStones;
}

sub blinkXTimes {
    my $x = shift;
    my $input = shift;
    my @splitInput = split / /, $input;
    for my $i(0..$x) {
        my @updatedInput = blink(@splitInput);
        @splitInput = @updatedInput;
    }
    return scalar @splitInput;
}

print blinkXTimes(24,"125 17")."\n";
print blinkXTimes(24,"2 77706 5847 9258441 0 741 883933 12")."\n";